[tasks.lint]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.doc]
command = "cargo"
args = ["doc", "--open", "--no-deps"]

#[tasks.build]
#command = "cargo"
#args = ["build"]
#dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
#dependencies = ["clean"]

[tasks.check-all]
dependencies = [
    "lint",
    "format",
    "check",
    "test"
]
